
# Omarchy Revision 1.7: feat(hyprland): configure multi-monitor for LG UltraGear 144Hz DP-7

# Omarchy Revision 2.27: feat(hyprland): configure multi-monitor for LG UltraGear 144Hz DP-7

# Omarchy Revision 3.47: feat(hyprland): configure multi-monitor for LG UltraGear 144Hz DP-7

# Omarchy Revision 4.67: feat(hyprland): configure multi-monitor for LG UltraGear 144Hz DP-7

# Omarchy Revision 5.87: feat(hyprland): configure multi-monitor for LG UltraGear 144Hz DP-7

# Omarchy Revision 6.107: feat(hyprland): configure multi-monitor for LG UltraGear 144Hz DP-7

# Omarchy Revision 7.127: feat(hyprland): configure multi-monitor for LG UltraGear 144Hz DP-7

# Omarchy Revision 8.147: feat(hyprland): configure multi-monitor for LG UltraGear 144Hz DP-7
